### ISSUE TITLE
Cannot find module - production build

### ISSUE THREAD

**Issue by hosnar** [paymoapp/electron-shutdown-handler#2]
Hi. This lib works fine when i test it on development, but if i build for production with electron-builder i get this error on app startup:
"Error: Cannot find module '@paymoapp/electron-shutdown-handler' Require stack: *pathToAppData*/app.asar/background.js".

It is not installed as dev dependency, so that shouldn't be an issue. Any idea what could be the problem? Thank you

**Comment by gergof** [comment]
Hello!
Do you use some kind of bundler for your electron main? Can you provide your electron-builder configuration?
