### ISSUE TITLE
Windows 11 can't stop

### ISSUE THREAD

**Issue by 07ke** [paymoapp/electron-shutdown-handler#3]
```javaScript
ElectronShutdownHandler.on('shutdown', async () => {
      logger.warn('shutdown quit 1')
     await sleep(3000) // = wind reg ProxyEnable
      logger.warn('shutdown quit 2')
      ElectronShutdownHandler.releaseShutdown()
      app.quit()
})
```

Now it shuts down when the "shutdown quit 2" is not executed

**Comment by gergof** [comment]
Hi!

First of all: did you execute the setup step? (as shown here: https://github.com/paymoapp/electron-shutdown-handler#example, setting up the window handle with `setWindowHandle` and calling `blockShutdown` afterwards)

If you don't call `blockShutdown` it can not be guaranteed that the async operations will be finished. Also note that blockShutdown __must__ be called before the actual shutdown event (before the callback is called).

**Comment by gergof** [comment]
Also! Please refer to the [demo](https://github.com/paymoapp/electron-shutdown-handler/blob/master/demo/electron.js). If you don't prevent the default behavior of `before-quit` and `close` events, then the electron app might just exit at a shutdown event, because even though `preventShutdown` is called, windows tries to close all the applications in the event of a shutdown.

**Comment by 07ke** [comment]
```javaScript

app.on('before-quit', e => {
     e.preventDefault();
});

win.on('close', e => {
     e.preventDefault();
});

function sleep(ms) {
   return new Promise(resolve => setTimeout(resolve, ms));
}

async function writeFile(text) {
return new Promise((resolve, reject) => {
	fs.writeFile('test.txt', text, (err) => {
		if (err) {
			reject(err);
		} else {
			resolve();
		}
	})
})
}

ShutdownHandler.setWindowHandle(win.getNativeWindowHandle());
ShutdownHandler.blockShutdown('Yayy! It works! Shutdown in 10 seconds');
writeFile('!!!!!!!!!!!!!!!!!!!!!!!!!!!');
ShutdownHandler.on('shutdown', async () => {
     await writeFile('! System is shutting down !');
     await sleep(10000);
     await writeFile('Shutting down NOW');
     ShutdownHandler.releaseShutdown();
     app.quit();
});
```

text.txt = ! System is shutting down ! 

"Shutting down NOW" No Write

**Comment by gergof** [comment]
I currently don't have a windows 11 system on hands, but I will look into this ASAP.

**Comment by ACCia** [comment]
It seems that the handling of Promise type is missing.
