### ISSUE TITLE
Where is rmlogotext.exe?

### ISSUE THREAD

**Issue by athenakia** [paymoapp/electron-shutdown-handler#5]
I cannot find rmlogotext.exe in the project, neither after running npm run build nor in the release files.

**Comment by gergof** [comment]
Rmlogotest is part of the windows App Certification Kit. The executable can be found here: `C:\Program Files (x86)\Windows Kits\10\App Certification Kit\rmlogotest.exe`

**Comment by athenakia** [comment]
I find it, thanks!
